apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot-mock-driver-restore
spec:
  storageClassName: test-csi-mock
  dataSource:
    name: csi-mock-snapshot-test 
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
